# Generated by Django 2.1.4 on 2019-01-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190105_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choise',
            new_name='choice_text',
        ),
    ]
